services:
  - type: web
    name: societas-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: societas-db
          property: connectionString
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: CLOUDINARY_CLOUD_NAME
        value: dii0wl9ke
      - key: CLOUDINARY_API_KEY
        value: 521365131889896
      - key: CLOUDINARY_API_SECRET
        value: bN5oAFXzoC-k-R31Z4Gxhd7Rngw

databases:
  - name: societas-db
    plan: free
    databaseName: societas
    user: societas